---
- name: Install package
  hosts: all
  become: true
  tasks:
    - name: Install selected package
      ansible.builtin.command:
        name:  "dnf install -y {{ package_name }}"
        state: present
